version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 466808333732.dkr.ecr.sa-east-1.amazonaws.com
      - REPOSITORY_URI=466808333732.dkr.ecr.sa-east-1.amazonaws.com/portifolio-efj
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t portifolio-efj .
      - docker tag portifolio-efj:latest 466808333732.dkr.ecr.sa-east-1.amazonaws.com/portifolio-efj:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 466808333732.dkr.ecr.sa-east-1.amazonaws.com/portifolio-efj:latest
      - echo Writing image definitions file...
      - printf '[{"name":"devops","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: 
      - imagedefinitions.json
